# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74543fccc06f14d0e357854eeb8e5e59e0e4ae144eebb5239da26d58c670ddfe9a36dd6bf522c239a70ec015591a912ed1b046a5d44ce4be32787ed7170862d7

test:
  secret_key_base: 8b37f9ac3332e954db8e26bcb6a0ef09e03d8df1c7efffa1703a3b25ff5c1e49744f4cb6072b1a0ff488dd1b0e9aa50826d8c90ef776a1ee5e166e740c343c10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
